default: &default
  redis_host: 127.0.0.1
  redis_port: 6379
  redis_timeout: 10
  redis_namespace: batchsan

development:
  <<: *default

test:
  <<: *default
  redis_namespace: batchsan-test

production:
  <<: *default
